apiVersion: v1
kind: Service
metadata:
  name: scholarbot-backend
  namespace: scholarbot
spec:
  selector:
    app: scholarbot-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
